### ISSUE TITLE
How to use it with immer?

### ISSUE THREAD

**Issue by shahreaz0** [zustandjs/zustand-slices#20]
Like this
![Screenshot_2024-05-25-20-33-41-74_f9ee0578fe1cc94de7482bd41accb329.jpg](https://github.com/zustandjs/zustand-slices/assets/44563789/f72fc84c-1f5d-46aa-afad-ffcfaf421166)

![Screenshot_2024-05-25-20-35-52-53_f9ee0578fe1cc94de7482bd41accb329.jpg](https://github.com/zustandjs/zustand-slices/assets/44563789/0a6f5d1f-745f-4022-8616-90f4b7416cc4)

**Comment by dai-shi** [comment]
This is probably opinionated, but I'd suggest to use `produce`.

```js
import { create } from 'zustand';
import { createSlice, withSlices } from 'zustand-slices';
import { produce } from 'immer';

const countSlice = createSlice({
  name: 'count',
  value: 0,
  actions: {
    inc: () => produce((draft) => { ++draft }),
    reset: () => () => 0,
  },
});
```
