### ISSUE TITLE
Slices + persist

### ISSUE THREAD

**Issue by Simoon-F** [zustandjs/zustand-slices#21]
In this example, if I only want to store countSlice , can it be adjusted like this?

https://t.co/7AognoqHWV

```ts
const useCountStore = create()((...config) => ({
  ...devtools(persist(withSlices(countSlice), { name: 'foo' }))(...config),
  ...withSlices(textSlice)(...config),
}));
```

**Comment by dai-shi** [comment]
I don't think it works. Did you try?

You should use `partialize` option with `persist`.

**Comment by Simoon-F** [comment]
@dai-shi In this example, I made a temporary adjustment, which turned out to be effective, but there was a TS type error prompt. I am not sure whether this method is correct, but subconsciously I think it seems not very elegant.

Yes, I am now using partialize to handle it
