### ISSUE TITLE
Provide example for partialize

### ISSUE THREAD

**Issue by Christopher96u** [zustandjs/zustand-slices#28]
It looks partialize works different using zustand-slices.

This is my slice

```js
import { createSliceWithImmer } from "zustand-slices/immer";

export const koalasSlice = createSliceWithImmer({
  name: "koalasStore",
  value: {
    koalas: 30,
    extraKoalas: 60,
    otherKoalas: 11,
  },
  actions: {
    incrementKoalas: () => (state) => {
      state.koalas += 1;
    },
    incrementKoalasBy: (quantity: number) => (state) => {
      state.koalas += quantity;
    },
  },
});

type PersistedKoalasSlice = Pick<typeof koalasSlice, "koalas">; // | "extraKoalas" | "otherKoalas"

export const partializeKoalasSlice = (
  store: typeof koalasSlice.value,
): PersistedKoalasSlice => ({
  koalas: store.koalas,
});
```

```js
import { create } from "zustand";
import { devtools, persist } from "zustand/middleware";
import { withSlices } from "zustand-slices";
import { catsSlice } from "./catsSlice";
import { koalasSlice, partializeKoalasSlice } from "./koalasSlice";
import { createJSONStorage } from "zustand/middleware";
import createZustandContext from "@/lib";

export const {
  StoreProvider: SessionStoreProvider,
  useStoreApi: useSesionStoreApi,
  useSelector: useSessionStoreSelector,
} = createZustandContext(() =>
  create(
    devtools(
      persist(withSlices(catsSlice, koalasSlice), {
        name: "SessionStore",
        storage: createJSONStorage(() => sessionStorage),
        // Add partialize
        //partialize: (store) => ({
        // add partials here
        //...partializeKoalasSlice(store.koalasStore),
        //}),
      }),
    ),
  ),
);
``` 

I'm dealing with the types again. Is there any helper type to type the partialize slices?

**Comment by dai-shi** [comment]
I think you overcomplicate things. The slice is defined from your type, so technically you can do this:
```ts
type PersistedKoalasSlice = { koalas: number };
```


See also: https://tsplay.dev/WyZnnw

**Comment by Christopher96u** [comment]
Hi @dai-shi , thanks for the example. i did some updates to keep the "store name" in the session/local storage too. Now it works like a champ. Any improvement?

`import { createSliceWithImmer } from "zustand-slices/immer";
// Utility to extract the value (state) from the slice
type ExtractValue<T extends { value: unknown }> = T["value"];

// Utility to extract the name (store name) from the slice
type ExtractName<T extends { name: string }> = T["name"];

// Reusable generic type that works with any slice and allows you to pick specific keys
type PersistedSlice<
  T extends { name: string; value: unknown },
  Keys extends keyof ExtractValue<T>,
> = {
  [K in ExtractName<T>]: Pick<ExtractValue<T>, Keys>;
};
export const koalasSlice = createSliceWithImmer({
  name: "koalasStore",
  value: {
    koalas: 30,
    extraKoalas: 60,
    otherKoalas: 11,
  },
  actions: {
    incrementKoalas: () => (state) => {
      state.koalas += 1;
    },
    incrementKoalasBy: (quantity: number) => (state) => {
      state.koalas += quantity;
    },
  },
});

type PersistedKoalasSlice = PersistedSlice<typeof koalasSlice, "koalas">;
export const partializeKoalasSlice = (
  store: typeof koalasSlice.value,
): PersistedKoalasSlice => ({
  koalasStore: {
    koalas: store.koalas,
  },
});
`

**Comment by dai-shi** [comment]
It depends on your goal, but I would just let TS infer types.

https://tsplay.dev/mbDZ9w

<img width="737" alt="image" src="https://github.com/user-attachments/assets/76b3c42a-72cd-4205-a2ab-7e80831a44ff">
